### ISSUE TITLE
Calendar no longer appears in Visualizations/Dashboards when table has date fields

### ISSUE THREAD

**Issue by mastropi** [Kranf99/kibella#65]
In previous versions of Kibella, a calendar used to appear at the top of Visualizations and Dashboards in order to easily filter on date fields when creating visualizations.

In fact, since dates must be stored in seconds in order for them to work correctly in the application, it is not easy to filter on dates using the free text box, and that's when the calendar comes handy.

I am basing my assumption that the calendar existed on the following:
- On 18-Jul-2016 I wrote among my task notes that a calendar appeared on dashboards even when no date field was present in the analyzed table.
- I created a couple of queries that I use in unit tests that have a filter on a date field.

**Comment by Kranf99** [comment]
Hello Daniel!
Do you mean this calendar:
![2020-01-10_011219](https://user-images.githubusercontent.com/20713234/72115143-4d8c7780-3346-11ea-949f-3ab872078793.png)
..because you can access it all the time by clicking here:
![2020-01-10_011326](https://user-images.githubusercontent.com/20713234/72115176-714fbd80-3346-11ea-8e48-97eaf8888bad.png)

**Comment by mastropi** [comment]
Yes, this is the calendar I meant.
It is not showing up in the Kibella 3 version I have downloaded on 16-Dec-2019 from http://download.timi.eu/Kibella/

But I see it in the Kibella 3 version that is available at http://anatella.com/kibella, so all good.

**Comment by mastropi** [comment]
The calendar no longer appears in the latest Kibella interface version dated 28-May-2020. See screenshot below.

![image](https://user-images.githubusercontent.com/12116544/87226407-d20e9000-c393-11ea-9244-13668254207e.png)

**Comment by mastropi** [comment]
I now realize that the calendar ONLY appears on Dashboards... but shouldn't we also include it in Visualization and Discover (a.k.a. Search) tab?

Otherwise, how can the user EASILY filter a visualization or Search on dates?

I am closing this issue and opening a new one on the above.
