### ISSUE TITLE
Remove non-relevant and non-implemented aggregations from X-axis aggregations

### ISSUE THREAD

**Issue by mastropi** [Kranf99/kibella#76]
**Goal:** Avoid users selecting an option that does not work.

This includes the followng 2 aggregations from the list shown in the picture:
- iPv4
- Significant terms

![image](https://user-images.githubusercontent.com/12116544/77342981-47951880-6d31-11ea-9b2a-e0e8549cf37f.png)

**Comment by Kranf99** [comment]
fixed with release v3.3
