### ISSUE TITLE
With some datasets, I can't plot numbers

### ISSUE THREAD

**Issue by dansotoz** [Kranf99/kibella#84]
I create any plot, as long as the count is displayed, it works, but no other metrics can be computed. All is declared numerical, no missings. Video is in the attached zip.
[Kibella Chart Error.zip](https://github.com/Kranf99/kibella/files/4654718/Kibella.Chart.Error.zip)

**Comment by mastropi** [comment]
@dansotoz This seems to be an error from the backend... (because the error message starts with "Error: unable to parse/serialize body")

Could you post the output from the debug window (F12) under the Network tab and Preview subtab?

The way to obtain this is by following these steps:
1) Go to the visualization that gives the error.
2) Press F12 -> A debug sub-window should open (at the bottom or at the right of the browser, as shown in the picture)
3) Run the visualization
4) Select Network among the tabs at the top, click on the last request shown in the requests list under "Name" (`_msearch`...) and select the "Preview" subtab appearing on the right of the request list.

You would probably see an error message showing up. But if everything went right (i.e. no error was generated by the backend), the response string should start with `{responses: ...`.

The picture below illustrates a response with no error.

![image](https://user-images.githubusercontent.com/12116544/82422935-63900e80-9a83-11ea-9c05-b78b4ddbbaaa.png)

**Comment by dansotoz** [comment]
"responses":[<br />
<b>Warning</b>:  array_key_exists() expects parameter 2 to be array, boolean given in <b>C:\soft\uwamp\www\kibella\JSON_SQL_Bridge\functionsauxkibella.php</b> on line <b>11</b><br />
{"took":0,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1146,"max_score":0,"hits":[]},"aggregations":{"2":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":200.0,"doc_count":1,"1":{"value":5001.0}},{"key":300.0,"doc_count":1,"1":{"value":3334.33333333333}},{"key":400.0,"doc_count":10,"1":{"value":2309.2609192542}},{"key":500.0,"doc_count":15,"1":{"value":1505.39563005897}},{"key":600.0,"doc_count":24,"1":{"value":1057.41988364931}},{"key":700.0,"doc_count":29,"1":{"value":873.560644787153}},{"key":900.0,"doc_count":34,"1":{"value":757.634142071111}},{"key":800.0,"doc_count":32,"1":{"value":725.167608153574}},{"key":1100.0,"doc_count":35,"1":{"value":617.081201822071}},{"key":1000.0,"doc_count":29,"1":{"value":606.520722286675}},{"key":1200.0,"doc_count":31,"1":{"value":528.967066289122}},{"key":1300.0,"doc_count":24,"1":{"value":526.699000579149}},{"key":1400.0,"doc_count":27,"1":{"value":460.158715608854}},{"key":1500.0,"doc_count":28,"1":{"value":438.730281631929}},{"key":1600.0,"doc_count":22,"1":{"value":433.433884944052}},{"key":1800.0,"doc_count":20,"1":{"value":393.300658687546}},{"key":2000.0,"doc_count":26,"1":{"value":368.503610300635}},{"key":1700.0,"doc_count":21,"1":{"value":345.9628341246}},{"key":1900.0,"doc_count":17,"1":{"value":345.04887393924}},{"key":2200.0,"doc_count":20,"1":{"value":319.169363223392}},{"key":2500.0,"doc_count":13,"1":{"value":273.893349703666}},{"key":2600.0,"doc_count":23,"1":{"value":273.598203237979}},{"key":3100.0,"doc_count":12,"1":{"value":271.18264227194}},{"key":2800.0,"doc_count":16,"1":{"value":270.966047231513}},{"key":2400.0,"doc_count":19,"1":{"value":267.223122134066}},{"key":2300.0,"doc_count":20,"1":{"value":247.63426528903}},{"key":2100.0,"doc_count":16,"1":{"value":247.157888238296}},{"key":3000.0,"doc_count":13,"1":{"value":236.773958563073}},{"key":3400.0,"doc_count":9,"1":{"value":235.114973646783}},{"key":3500.0,"doc_count":14,"1":{"value":228.97708935059}},{"key":4000.0,"doc_count":12,"1":{"value":211.821797035326}},{"key":2700.0,"doc_count":13,"1":{"value":207.415417422169}},{"key":3800.0,"doc_count":8,"1":{"value":203.453663656875}},{"key":2900.0,"doc_count":14,"1":{"value":195.319679293974}},{"key":4300.0,"doc_count":11,"1":{"value":194.603397782951}},{"key":3200.0,"doc_count":15,"1":{"value":193.36475670353}},{"key":5500.0,"doc_count":7,"1":{"value":182.818181818182}},{"key":3300.0,"doc_count":12,"1":{"value":180.638209118808}},{"key":4800.0,"doc_count":7,"1":{"value":179.927268661683}},{"key":5000.0,"doc_count":7,"1":{"value":175.866300225465}},{"key":4500.0,"doc_count":8,"1":{"value":172.572032196147}},{"key":5900.0,"doc_count":7,"1":{"value":170.491525423729}},{"key":5400.0,"doc_count":10,"1":{"value":170.070309552706}},{"key":4700.0,"doc_count":14,"1":{"value":169.628204001755}},{"key":4400.0,"doc_count":15,"1":{"value":169.21470290955}},{"key":3600.0,"doc_count":11,"1":{"value":157.610324696247}},{"key":5300.0,"doc_count":5,"1":{"value":156.751891419871}},{"key":5700.0,"doc_count":7,"1":{"value":154.807514674968}},{"key":4600.0,"doc_count":3,"1":{"value":153.962171075792}},{"key":5200.0,"doc_count":9,"1":{"value":153.260584317106}},{"key":5100.0,"doc_count":8,"1":{"value":152.628872582515}},{"key":6600.0,"doc_count":4,"1":{"value":152.515151515151}},{"key":3900.0,"doc_count":12,"1":{"value":152.248273825277}},{"key":3700.0,"doc_count":13,"1":{"value":140.019283103495}},{"key":7200.0,"doc_count":2,"1":{"value":139.888888888889}},{"key":6400.0,"doc_count":7,"1":{"value":138.356633354192}},{"key":6300.0,"doc_count":6,"1":{"value":134.274025957646}},{"key":6500.0,"doc_count":6,"1":{"value":133.204101611024}},{"key":4900.0,"doc_count":8,"1":{"value":132.653546334528}},{"key":6000.0,"doc_count":4,"1":{"value":132.002222388479}},{"key":4100.0,"doc_count":8,"1":{"value":131.370696048401}},{"key":7000.0,"doc_count":8,"1":{"value":128.997903670365}},{"key":4200.0,"doc_count":6,"1":{"value":127.35936177247}},{"key":5800.0,"doc_count":7,"1":{"value":126.626047904239}},{"key":7100.0,"doc_count":7,"1":{"value":125.150274079626}},{"key":8100.0,"doc_count":4,"1":{"value":124.456790123457}},{"key":6800.0,"doc_count":5,"1":{"value":123.444469453387}},{"key":6900.0,"doc_count":6,"1":{"value":123.304559565647}},{"key":8300.0,"doc_count":1,"1":{"value":121.481927710843}},{"key":6700.0,"doc_count":4,"1":{"value":118.93758944032}},{"key":5600.0,"doc_count":8,"1":{"value":117.631480675777}},{"key":7300.0,"doc_count":5,"1":{"value":115.384709629924}},{"key":6200.0,"doc_count":6,"1":{"value":114.582057959367}},{"key":6100.0,"doc_count":9,"1":{"value":114.315186296178}},{"key":8900.0,"doc_count":4,"1":{"value":113.359550561798}},{"key":7600.0,"doc_count":6,"1":{"value":111.864696475467}},{"key":8000.0,"doc_count":7,"1":{"value":111.567126923915}},{"key":9200.0,"doc_count":2,"1":{"value":109.695652173913}},{"key":9400.0,"doc_count":2,"1":{"value":107.382978723404}},{"key":7700.0,"doc_count":5,"1":{"value":107.356154264735}},{"key":9500.0,"doc_count":3,"1":{"value":106.263157894737}},{"key":7400.0,"doc_count":4,"1":{"value":105.262742102484}},{"key":9600.0,"doc_count":3,"1":{"value":105.166666666667}},{"key":9700.0,"doc_count":3,"1":{"value":104.092783505155}},{"key":7800.0,"doc_count":4,"1":{"value":103.146836122307}},{"key":9900.0,"doc_count":2,"1":{"value":102.010101010101}},{"key":10000.0,"doc_count":1,"1":{"value":101.0}},{"key":10200.0,"doc_count":4,"1":{"value":99.0392156862745}},{"key":8600.0,"doc_count":5,"1":{"value":98.8162349632028}},{"key":8500.0,"doc_count":5,"1":{"value":97.5305322736257}},{"key":9100.0,"doc_count":6,"1":{"value":96.5687233623067}},{"key":10500.0,"doc_count":1,"1":{"value":96.2380952380952}},{"key":10600.0,"doc_count":3,"1":{"value":95.3396226415094}},{"key":7500.0,"doc_count":6,"1":{"value":94.7416063535119}},{"key":10800.0,"doc_count":1,"1":{"value":93.5925925925926}},{"key":8400.0,"doc_count":4,"1":{"value":93.1319269267003}},{"key":10900.0,"doc_count":1,"1":{"value":92.743119266055}},{"key":11000.0,"doc_count":1,"1":{"value":91.9090909090909}},{"key":8200.0,"doc_count":3,"1":{"value":90.2901592826965}},{"key":7900.0,"doc_count":3,"1":{"value":88.3159091658213}},{"key":11500.0,"doc_count":1,"1":{"value":87.9565217391304}},{"key":11600.0,"doc_count":2,"1":{"value":87.2068965517241}},{"key":11700.0,"doc_count":1,"1":{"value":86.4700854700855}},{"key":11800.0,"doc_count":2,"1":{"value":85.7457627118644}},{"key":11900.0,"doc_count":2,"1":{"value":85.0336134453782}},{"key":8800.0,"doc_count":3,"1":{"value":84.7454282607889}},{"key":8700.0,"doc_count":7,"1":{"value":84.6876104984705}},{"key":12000.0,"doc_count":2,"1":{"value":84.3333333333333}},{"key":12100.0,"doc_count":1,"1":{"value":83.6446280991736}},{"key":12200.0,"doc_count":2,"1":{"value":82.9672131147541}},{"key":12400.0,"doc_count":2,"1":{"value":81.6451612903226}},{"key":10100.0,"doc_count":4,"1":{"value":81.2467906230206}},{"key":12600.0,"doc_count":1,"1":{"value":80.3650793650794}},{"key":12900.0,"doc_count":1,"1":{"value":78.5193798449613}},{"key":13100.0,"doc_count":2,"1":{"value":77.3358778625954}},{"key":9800.0,"doc_count":3,"1":{"value":77.0133952137984}},{"key":13200.0,"doc_count":1,"1":{"value":76.7575757575758}},{"key":13300.0,"doc_count":3,"1":{"value":76.187969924812}},{"key":13500.0,"doc_count":1,"1":{"value":75.0740740740741}},{"key":13800.0,"doc_count":1,"1":{"value":73.463768115942}},{"key":13900.0,"doc_count":1,"1":{"value":72.9424460431655}},{"key":14000.0,"doc_count":2,"1":{"value":72.4285714285714}},{"key":14100.0,"doc_count":1,"1":{"value":71.9219858156028}},{"key":14200.0,"doc_count":2,"1":{"value":71.4225352112676}},{"key":10700.0,"doc_count":3,"1":{"value":71.290517614393}},{"key":9300.0,"doc_count":5,"1":{"value":71.0878960520219}},{"key":14300.0,"doc_count":1,"1":{"value":70.9300699300699}},{"key":14400.0,"doc_count":1,"1":{"value":70.4444444444444}},{"key":14500.0,"doc_count":2,"1":{"value":69.9655172413793}},{"key":14700.0,"doc_count":1,"1":{"value":69.0272108843537}},{"key":14800.0,"doc_count":1,"1":{"value":68.5675675675676}},{"key":14900.0,"doc_count":1,"1":{"value":68.1140939597315}},{"key":15600.0,"doc_count":1,"1":{"value":65.1025641025641}},{"key":10300.0,"doc_count":5,"1":{"value":64.6667040035229}},{"key":15900.0,"doc_count":2,"1":{"value":63.8930817610063}},{"key":9000.0,"doc_count":2,"1":{"value":62.7003693862482}},{"key":16300.0,"doc_count":2,"1":{"value":62.3496932515337}},{"key":16900.0,"doc_count":1,"1":{"value":60.1715976331361}},{"key":12300.0,"doc_count":3,"1":{"value":59.2938359463921}},{"key":17200.0,"doc_count":1,"1":{"value":59.1395348837209}},{"key":17800.0,"doc_count":1,"1":{"value":57.1797752808989}},{"key":18000.0,"doc_count":1,"1":{"value":56.5555555555556}},{"key":18100.0,"doc_count":1,"1":{"value":56.2486187845304}},{"key":18500.0,"doc_count":1,"1":{"value":55.0540540540541}},{"key":19000.0,"doc_count":1,"1":{"value":53.6315789473684}},{"key":10400.0,"doc_count":2,"1":{"value":53.4579589660016}},{"key":20400.0,"doc_count":1,"1":{"value":50.0196078431373}},{"key":20800.0,"doc_count":2,"1":{"value":49.0769230769231}},{"key":21300.0,"doc_count":1,"1":{"value":47.9483568075117}},{"key":23600.0,"doc_count":1,"1":{"value":43.3728813559322}},{"key":24100.0,"doc_count":1,"1":{"value":42.49377593361}},{"key":24500.0,"doc_count":1,"1":{"value":41.8163265306122}},{"key":26700.0,"doc_count":1,"1":{"value":38.4531835205993}},{"key":27400.0,"doc_count":1,"1":{"value":37.4963503649635}},{"key":31200.0,"doc_count":1,"1":{"value":33.051282051282}},{"key":31900.0,"doc_count":1,"1":{"value":32.3479623824451}},{"key":33800.0,"doc_count":1,"1":{"value":30.585798816568}},{"key":38600.0,"doc_count":1,"1":{"value":26.9067357512953}},{"key":11400.0,"doc_count":1,"1":{"value":24.9540728057703}},{"key":12700.0,"doc_count":1,"1":{"value":24.952059364519}},{"key":17100.0,"doc_count":1,"1":{"value":24.949237551092}},{"key":45000.0,"doc_count":1,"1":{"value":23.2222222222222}},{"key":53900.0,"doc_count":1,"1":{"value":19.5528756957328}},{"key":16600.0,"doc_count":1,"1":{"value":12.5667613164364}},{"key":20600.0,"doc_count":1,"1":{"value":9.74983664226364}}]}}}]}

**Comment by mastropi** [comment]
Thanks @dansotoz for sending this piece of information.

It seems there is a problem with the metadata information of the dataset you are using to generate the plot.

Could you check if the dataset exists in the internal database `kibella.sqlite` that stores all datasets registered in Kibella? You should look inside the table called `RegisteredTables` in `www/kibella/tempdata/kibella.sqlite` (assuming kibella is installed in your `www` directory).

If it is not there (*you should look in column `_id` and check if the ID coincides with the one appearing when you navigate to the Settings -> Datasets tab in Kibella*), you can register the dataset again via the Administration tab in Kibella.

![image](https://user-images.githubusercontent.com/12116544/83327951-13cdf600-a280-11ea-8778-1ec3acee821a.png)

If the ID shows up there, then I don't know the reason leading to the WARNING message showing up in the response. I would need more information to investigate more, in which case we could arrange a call.

And if you want a quick solution to this problem, you can edit the `functionsauxkibella.php` associated to the warning (which is "encrypted") and add `@` at the front of the two occurrences of the `array_key_exists()` function you will see there (e.g. `@array_key_exists(...)`). This will eliminate all warning or error messages issued by the call to that function, and you should get the correct response sent to the client to display the graph.

**Comment by mastropi** [comment]
@dansotoz: I figured out why you were having this problem only on your dataset and not for instance in the `income`  dataset: the variables in your dataset are all numeric, right?

In any case, that problem is solved in the latest release of the JSON-SQLite bridge uploaded to the respective repository on Monday 01-Jun-2020. It only has to be integrated to Kibella and a  new Kibella version released.
