### ISSUE TITLE
[Admin] Add a mechanism to unregister a dataset

### ISSUE THREAD

**Issue by mastropi** [Kranf99/kibella#89]
Currently [(Kibella-v3.4](https://github.com/Kranf99/kibella/releases/tag/v3.4)) there is no way the user can unregister a dataset, for example when they delete a dataset from their database or when they delete the database altogether.

On the other hand, they may no longer wish to have certain datasets listed as accessible any more.

_It would be nice if the unregistration functionality **allows to unregister a set of datasets that all sit in the same database**._

**Comment by Kranf99** [comment]
It's already there:
![2020-06-25_205454](https://user-images.githubusercontent.com/20713234/85781651-35f35080-b726-11ea-8393-88f679765394.png)

**Comment by mastropi** [comment]
Excellent. And it's already implemented in the backend! 😄
