### ISSUE TITLE
[Pie Chart] Improve colors: indistinguishable groups with the default sequential color scheme

### ISSUE THREAD

**Issue by mastropi** [Kranf99/kibella#90]
All colors except category "Other" are indistinguishable with the default options of a Pie Chart.

Note that the default options use a ***sequential coloring*** scheme, which may ***not be the best option for nominal categorical data*** (the most common case).

In addition to fixing the squential color scheme, **should we set the *categorical color scheme* as the default**?

[Kibella-v3.4](https://github.com/Kranf99/kibella/releases/tag/v3.4) (28-May-2020)

![image](https://user-images.githubusercontent.com/12116544/83413654-7bb94380-a41c-11ea-8964-4819fddf2b0e.png)

**Comment by Kranf99** [comment]
done in v3.5
