### ISSUE TITLE
[Pie Chart] Duplicated "Other" category shows up in dashboard

### ISSUE THREAD

**Issue by mastropi** [Kranf99/kibella#91]
The "Other" category appears twice when the pie chart is in the dashboard. The "second" time it appears has an associated count equal to the total number of cases in the dataset. See screenshot.

At least, this is observed when opening the INCOME Example dashboard. If we remove the visualization from the dashboard and add it back, the correct pie chart is shown.

[Kibella-v3.4](https://github.com/Kranf99/kibella/releases/tag/v3.4) (28-May-2020)

![image](https://user-images.githubusercontent.com/12116544/83414307-8f18de80-a41d-11ea-9355-e498f2fc1511.png)

**Comment by Kranf99** [comment]
this seems ok in v3.5

**Comment by Kranf99** [comment]
the problem is still there: As soon as a filter is applied the "other" category takes 50% of the space:
![image007](https://user-images.githubusercontent.com/20713234/99397619-98223d00-28e3-11eb-8eb9-f7fe600bea10.png)

**Comment by mastropi** [comment]
The problem happens only when the `Display "Other" bucket` option is checked (which is the default).

And the issue most likely happens because one of the categories in the `race` field of the `Income` dataset is precisely equal to “Other”…

![image](https://user-images.githubusercontent.com/12116544/99404643-a57efd80-28ca-11eb-8308-b7c7af3be34d.png)

**Comment by Kranf99** [comment]
I created the issue 110 to fix this.
(with a more precise explanation of the bug)
