### ISSUE TITLE
Kibella home page does not work

### ISSUE THREAD

**Issue by mastropi** [Kranf99/kibella#92]
When we click on the Kibella icon at the top left of the screen (which points to `localhost/kibella`) we get the following error screen.

![image](https://user-images.githubusercontent.com/12116544/83739624-22d4ef80-a656-11ea-8b3b-bf857ba01a8f.png)

I noticed that the request from this page reads: `localhost/kibella//db`
i.e. there are ***two slashes*** (instead of one) separating the words `kibella` and `db`.

The workaround to this error was to add the following Apache directive to the UWAMP Apache configuration:
`AliasMatch "^/kibella//db(.*)$" "{DOCUMENTPATH}/kibella/JSON_SQL_Bridge/requests.php"`

However, after doing this change a new error screen is displayed:
![image](https://user-images.githubusercontent.com/12116544/83740155-bf978d00-a656-11ea-8ddb-6cd0b37471b1.png)

**NOTE ALSO that the error message reads "Kibana" instead of "Kibella"**.

[Kibella-v3.4](https://github.com/Kranf99/kibella/releases/tag/v3.4) (28-May-2020)

**Comment by Kranf99** [comment]
this url has no reason to exists anymore. I just removed it.
